# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ORMEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PREGRADO', 'Pregrado'), ('MAESTRIA', 'Maestria'), ('DOCTORADO', 'Doctorado')], max_length=20)),
            ],
        ),
    ]
