DEFAULT_PAGINATOR_PAGE = 1
DEFAULT_PAGINATOR_PAGE_SIZE = 5
ESTUDIANTE_TIPO_PREGRADO = 'PREGRADO'
ESTUDIANTE_TIPO_MAESTRIA = 'MAESTRIA'
ESTUDIANTE_TIPO_DOCTORADO = 'DOCTORADO'
ESTUDIANTE_TIPO_CHOICES = (
    (ESTUDIANTE_TIPO_PREGRADO, 'Pregrado'),
    (ESTUDIANTE_TIPO_MAESTRIA, 'Maestria'),
    (ESTUDIANTE_TIPO_DOCTORADO, 'Doctorado'),
)